### ISSUE TITLE
[BUG] Cannot claim reward

### ISSUE THREAD

**Issue by mchl18** [RebelliousToken/RebelliousWallet#3]
Hello,

I have an outstanding reward which I would like to claim via the Rebellious Wallet.
I have 0.015 Eth in my Wallet and when I click "claim reward" the button goes grey for a few seconds and then goes back to blue again, no change in balances.

Wallet: v 0.0.1
OSX: v 10.13.2

**Comment by RebelliousToken** [comment]
Hello @mchl18,

Fixed in v.0.0.2, now you can select optimal gas price for your stake reward transaction.

Best regards,
Rebellious Team
