### ISSUE TITLE
sending rebl don't work / claiming reward dont work too 

### ISSUE THREAD

**Issue by nairyl** [RebelliousToken/RebelliousWallet#4]
Hi everybody since few days i trying to transfert my token but nothing work 
everytime i get this message : Error: Transaction was not mined within 50 blocks, please make sure your transaction was properly send. Be aware that it might still be mined!
It look like gas coast is too low maybe ?
somebody can help ?

Thx Mate ..wish all the best to our new blockchain @all team 

Ps i stay in back and wait new developpement for helping by translation (French) please feel free to ask any help ;-)

**Comment by nairyl** [comment]
OS -> Debian linux 
Eth port router status (30303) : opened

**Comment by nairyl** [comment]
is it possible to set gas coast directly in hard code ?

**Comment by RebelliousToken** [comment]
Hello @nairyl,

Fixed in v.0.0.2, now you can set gas price using slider in wallet interface.

Best regards,
Rebellious Team
