### ISSUE TITLE
Cannot collect reward after day 10

### ISSUE THREAD

**Issue by sugardave** [RebelliousToken/RebelliousWallet#6]
I have v0.0.3.  I collected my last reward 13 days ago (13 > 10).  The "Collect Reward" button is disabled.

![screen shot 2018-03-14 at 11 29 09 am](https://user-images.githubusercontent.com/192353/37416219-375d9b2a-277b-11e8-9ef1-8b5fb6a70b0b.png)

**Comment by ralphhm** [comment]
With the change from contract staking to staking via API call (sending the stake reward from pool that could not be burned) the minimum staking time was changed from 10 to 30 days (you can even see this in your screenshot: "13/30"). This means you need to wait 17 more days until the button is activated and you can get the reward. This is intended behavior and this issue can be closed.

**Comment by sugardave** [comment]
Ah, thank you, I didn't notice the missing "max reward" text.
